added firewall installation

diff --git a/quarry b/quarry
--- a/quarry
+++ b/quarry
@@ -1,15 +1,35 @@
 #!/bin/bash
 set -e
+# where our pluginhook plugins live - each 'commands' file extends the main script
 export PLUGIN_PATH=${PLUGIN_PATH:="/var/lib/quarry/plugins"}
+# the local folder in which our running quarry stacks live
 export QUARRY_APPS=${QUARRY_APPS:="/home/quarry"}
+# make sure we have docker installed
+docker version >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
 
-function generate_port()
-{
-  RANDOM_PORT=`shuf -i 2000-65000 -n 1`;
-  if [[ -n `netstat -ant | grep :$RANDOM_PORT` ]]; then
-    generate_port
-  fi
-}
+#function generate_port()#{
+#  RANDOM_PORT=`shuf -i 2000-65000 -n 1`;
+#  if [[ -n `netstat -ant | grep :$RANDOM_PORT` ]]; then
+#    generate_port
+#  fi
+#}
+
+#function container_ip()#{
+#  CONTAINER_IP=`docker inspect $1 | grep IPAddress | sed -r 's/\s+"IPAddress": "(([0-9]{1,3}\.){3}[0-9]{1,3})",/\1/'`
+#}
+
+#function install_image {
+#  # we surpress output for the hipache container cos it breaks otherwise
+#  if [ ! -d ~/quarryfiles/$1 ]; then
+#    echo "$1 is not a quarryfile" && exit 1
+#  fi
+#  flags=""
+#  if [ "$1" = 'hipache' ]; then
+#    flags=" -q"
+#  fi
+#  echo "building image $1"
+#  echo "build $flags -t quarry/$1 ~/quarryfiles/$1"
+#}
 
 case "$1" in
   receive)
@@ -31,17 +51,6 @@ case "$1" in
     #echo
     ;;
 
-  build)
-    IMAGE="$2"
-    #id=$(cat | docker run -i -a stdin quarry/builder /bin/bash -c "mkdir -p /app && tar -xC /app")
-    #test $(docker wait $id) -eq 0
-    #docker commit $id $IMAGE > /dev/null
-    #id=$(docker run -d $IMAGE /build/builder)
-    #docker attach $id
-    #test $(docker wait $id) -eq 0
-    #docker commit $id $IMAGE > /dev/null
-    ;;
-
   release)
     APP="$2"; IMAGE="$3"
     #pluginhook pre-release $APP $IMAGE
@@ -51,28 +60,6 @@ case "$1" in
     #  docker commit $id $IMAGE > /dev/null
     #fi
     #pluginhook post-release $APP $IMAGE
-    ;;
-
-  ensureapp)
-    APP="$2";
-
-    if [[ ! -f "$QUARRY_APPS/$APP" ]]; then
-      mkdir -p "$QUARRY_APPS/$APP/pids"
-      mkdir -p "$QUARRY_APPS/$APP/logs"
-      mkdir -p "$QUARRY_APPS/$APP/env"
-      mkdir -p "$QUARRY_APPS/$APP/disk"
-
-      folders=( services nodes disks )
-      for IMAGE in "${QUARRYFILES_IMAGES[@]}"
-      do
-        install_image $IMAGE
-      done
-    fi
-    ;;
-
-  service)
-    APP="$2"; TYPE="$3"
-    quarry ensureapp $APP
     ;;
 
   deploy)
@@ -96,17 +83,6 @@ case "$1" in
     #pluginhook post-deploy $APP $port
     ;;
 
-  cleanup)
-    # delete all non-running container
-    docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &
-    # delete unused images
-    docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
-    # delete quarry images
-    docker images | grep 'quarry/' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
-    # remove the image cache
-    rm -rf ~/quarryfiles
-    ;;
-
   plugins)
     ls -1 -d $PLUGIN_PATH/*/
     ;;
@@ -117,11 +93,22 @@ case "$1" in
 
   # temporary hack for https://github.com/progrium/dokku/issues/82
   deploy:all)
-    for app in $(ls -d $HOME/*/); do
-      APP=$(basename $app);
-      IMAGE="app/$APP"
-      dokku deploy $APP $IMAGE
-    done
+    #for app in $(ls -d $HOME/*/); do
+    #  APP=$(basename $app);
+    #  IMAGE="app/$APP"
+    #  dokku deploy $APP $IMAGE
+    #done
+    #;;
+
+  cleanup)
+    # delete all non-running containers
+    #docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &
+    # delete unused images
+    #docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
+    # delete quarry images
+    #docker images | grep 'quarry/' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
+    # remove the image cache
+    #rm -rf ~/quarryfiles
     ;;
 
   help)
@@ -131,11 +118,6 @@ case "$1" in
     plugins-install Install active plugins
 EOF
     ;;
-
-  port)
-    generate_port
-    echo $RANDOM_PORT
-    ;;    
 
   *)
     pluginhook commands "$@"
